#!/usr/bin/env python3
"""Refresh `_data/forpublicai_repos.yml` from the GitHub org API.

The navbar classifies repos as recently active / active / quiet from the
`pushed_at` timestamps in that file. This script keeps those timestamps
current so the buckets do not go stale between site deploys.

Usage:
    python3 scripts/sync_repos.py

Optional environment:
    GITHUB_TOKEN or GH_TOKEN  authenticated requests (used in GitHub Actions)
    GITHUB_ORG                org to list (default: forpublicai)
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from typing import Any

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(ROOT, "_data", "forpublicai_repos.yml")
DEFAULT_ORG = "forpublicai"
API_ACCEPT = "application/vnd.github+json"
API_VERSION = "2022-11-28"
USER_AGENT = "publicai.network-repo-sync/1.0"


def github_headers() -> dict[str, str]:
    headers = {
        "Accept": API_ACCEPT,
        "X-GitHub-Api-Version": API_VERSION,
        "User-Agent": USER_AGENT,
    }
    token = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def parse_next_link(link_header: str | None) -> str | None:
    if not link_header:
        return None
    for part in link_header.split(","):
        section = part.strip()
        if 'rel="next"' not in section:
            continue
        start = section.find("<")
        end = section.find(">", start + 1)
        if start != -1 and end != -1:
            return section[start + 1 : end]
    return None


def fetch_json(url: str) -> tuple[Any, str | None]:
    req = urllib.request.Request(url, headers=github_headers())
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
            return payload, parse_next_link(resp.headers.get("Link"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API error {e.code} for {url}: {detail}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Failed to reach GitHub API at {url}: {e}") from e


def fetch_org_repos(org: str) -> list[dict[str, Any]]:
    url = f"https://api.github.com/orgs/{org}/repos?per_page=100&sort=pushed&direction=desc"
    repos: list[dict[str, Any]] = []
    while url:
        page, next_url = fetch_json(url)
        if not isinstance(page, list):
            raise RuntimeError(f"Unexpected GitHub API response for {url}: {page!r}")
        repos.extend(item for item in page if isinstance(item, dict))
        url = next_url
    return repos


ISO_DATETIME = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")


def yaml_scalar(value: str) -> str:
    if value == "":
        return '""'
    # Keep GitHub timestamps unquoted so Jekyll/Liquid can treat them as dates.
    if ISO_DATETIME.match(value):
        return value
    needs_quotes = (
        value != value.strip()
        or value[0] in "-?:{}[]|>&*!%@`'\","
        or any(ch in value for ch in ":#{}[]&*!|>%@`'\"\n")
        or value.lower() in {"true", "false", "null", "yes", "no", "on", "off"}
    )
    if needs_quotes:
        return json.dumps(value, ensure_ascii=False)
    return value


def repo_record(repo: dict[str, Any]) -> dict[str, str] | None:
    name = repo.get("name")
    html_url = repo.get("html_url")
    pushed_at = repo.get("pushed_at")
    updated_at = repo.get("updated_at")
    if not isinstance(name, str) or not name:
        return None
    if not isinstance(html_url, str) or not html_url:
        return None
    if not isinstance(pushed_at, str) or not isinstance(updated_at, str):
        return None
    if repo.get("archived") or repo.get("disabled"):
        return None

    record = {
        "name": name,
        "url": html_url,
        "pushed_at": pushed_at,
        "updated_at": updated_at,
    }
    description = repo.get("description")
    if isinstance(description, str) and description.strip():
        record["description"] = description.strip()
    homepage = repo.get("homepage")
    if isinstance(homepage, str) and homepage.strip():
        record["homepage"] = homepage.strip()
    return record


def render_yaml(records: list[dict[str, str]]) -> str:
    lines = [
        "# Auto-generated by scripts/sync_repos.py from the GitHub org API.",
        "# Do not edit by hand. Re-run the script or the sync-repos workflow.",
        "",
    ]
    field_order = ("name", "url", "description", "homepage", "pushed_at", "updated_at")
    for i, record in enumerate(records):
        if i:
            lines.append("")
        first = True
        for field in field_order:
            if field not in record:
                continue
            prefix = "- " if first else "  "
            lines.append(f"{prefix}{field}: {yaml_scalar(record[field])}")
            first = False
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    org = os.getenv("GITHUB_ORG", DEFAULT_ORG).strip() or DEFAULT_ORG
    records = [r for r in (repo_record(repo) for repo in fetch_org_repos(org)) if r]
    records.sort(key=lambda r: r["pushed_at"], reverse=True)
    if not records:
        print(f"No public repositories found for org {org}.", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    new_text = render_yaml(records)
    old_text = ""
    if os.path.exists(OUTPUT_PATH):
        with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
            old_text = f.read()

    if new_text == old_text:
        print(f"No repository updates needed ({len(records)} repos).")
        return 0

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    print(f"Updated {os.path.relpath(OUTPUT_PATH, ROOT)} with {len(records)} repos.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
